services:
  redis:
    image: redis:6

  app:
    image: registry:2
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - ../certs/cluster:/certs:ro
      - data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml

volumes:
  data:
