version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - send_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker

  app:
    image: pi-cluster-main:5000/timvisee/send:latest
    depends_on:
      - redis
    networks:
      - send_net
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - HOST=langbotten.ddns.net
      - BASE_URL=https://langbotten.ddns.net
      - PORT=8080
      - FILE_DIR=/data
      - REDIS_HOST=redis
    volumes:
        - /mnt/send_storage:/data
    deploy:
      mode: global
    #   replicas: 4
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker

networks:
  send_net:
    driver: overlay
    attachable: true
